version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    container_name: backend_container
    ports:
      - '8080:8080'
    volumes:
      - ./Backend:/app/Backend
      - /app/backend/node_modules
    environment:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
